### ISSUE TITLE
Parity between single and multiple key retrieval steps (converting key to a value)

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#107]
According to "The steps for retrieving multiple keys from an object store with store, range and optional count", each entry is to be the result of running "the steps to convert a key to a value with record’s key."

However, for "The steps for retrieving a key from an object store with store and range", however, there is no requirement listed for doing such a key-to-value conversion.

While I'm unclear whether any such conversion should have already taken place anyways, I thought I'd mention it in case this apparent inconsistency was problematic.

**Comment by inexorabletash** [comment]
Yeah, that should probably be corrected. It also applies to __steps for retrieving a value from an index__ since an index's value is a key. (And I should add an informative note there explaining that, since it confused me when I started working with the spec.)

... the other operations should be updated too where they simply return a key, since it's not explicit anywhere else that the conversion should be invoked.
