### ISSUE TITLE
Behavior tested by transaction-abort-multiple-metadata-revert.html is not obviously specified anywhere

### ISSUE THREAD

**Issue by beidson** [w3c/IndexedDB#109]
Behavior tested by transaction-abort-multiple-metadata-revert.html is not obviously specified anywhere

That's vague and is a mouthful, so let me explain.

This test creates some object stores, and each objectstore has an index.

At one point in the test, it:
1 - Grabs an object store handle.
2 - Deletes the references object store (which has an index)
3 - Verifies that the object store handle's set of index names is empty:
`
        database.deleteObjectStore('not_books');
...
        assert_array_equals(
            store.indexNames, [],
            'IDBObjectStore.indexNames for the deleted store3 should be empty ' +
            'immediately after IDBDatabase.deleteObjectStore() returns');
`
The problem is... I can't find where this behavior is actually specified.

Looking at the steps for IDBDatabase.deleteObjectStore, looking at behavior for "object store handle" or "index set" and other related terms... I can find nothing that states that once an object store is deleted that the object store handles referencing it should have their indexNames set cleared out.

Note: I'm not arguing with the behavior. The behavior might make sense. I see that it could go either way but don't feel strongly about it.

I'm just arguing that the behavior is either:
1 - Not specified
2 - Specified, but in a non-obvious way, and that we should make it more obvious.

**Comment by inexorabletash** [comment]
Agreed, this is underspecified. I'll propose text here.

The overall test was probably written to verify the steps in https://w3c.github.io/IndexedDB/#abort-upgrade-transaction which *revert* the clearing, which apparently implementations did, but the clearing you note in step 3 itself isn't described. I believe @pwnall verified that the behavior matched in Chrome and Firefox, so I guess we should keep it.

(I also agree in the abstract that it could go either way. I'm also not a fan of how "handles" revert following an abort rather than just holding stale data but I got outvoted on that one back in "v1". Oh well.)

The distinction between "object store handle" and "object store" (etc) is something that didn't exist in the "v1" spec and even more behavior like this was underspecified. There is almost certainly more I missed so please keep feedback like this coming! (Things like "Destroy store" could also be more rigorous; as I stare at it I'm not sure that actually has any meaning.)

**Comment by inexorabletash** [comment]
(Oh, and of course PRs welcome if anyone wants to propose text here!)

**Comment by beidson** [comment]
>(Things like "Destroy store" could also be more rigorous; as I stare at it I'm not sure that actually has any meaning.)

Yah, I figured the answer would be there, but certainly couldn't find any definition.

**Comment by beidson** [comment]
Okay, yes I agree the behavior in "steps for aborting an upgrade transaction" match whats being tested.
