### ISSUE TITLE
Horizontal review…

### ISSUE THREAD

**Issue by chaals** [w3c/IndexedDB#112]
A tracking issue to ensure we have got review for important "horizontal" topics

- [x] Accessibility
- [ ] Security
- [x] Privacy
- [x] Architecture
- [x] Internationalisation ([1 Open](https://github.com/w3c/IndexedDB/labels/i18n-comment), 7 Closed)

(If there are more we should have please edit this comment)

**Comment by chaals** [comment]
APA accessibility review says ["no problems"](https://lists.w3.org/Archives/Public/public-apa/2016Nov/0016.html)

**Comment by LJWatson** [comment]
Offlist email from Tara Whalen on 17th Jan confirms no issues from the Privacy IG.

**Comment by LJWatson** [comment]
Track the <a href="https://github.com/w3c/i18n-activity/issues/281">i18n review</a>.

**Comment by inexorabletash** [comment]
FYI, two related TAG reviews:
* https://github.com/w3ctag/spec-reviews/issues/153
* https://github.com/w3ctag/spec-reviews/issues/84

**Comment by inexorabletash** [comment]
Re: I18n - @aphillips did a substantial review and filed issues. Does that check the box or are we awaiting a more positive assertion somewhere?

**Comment by LJWatson** [comment]
I can't update @Chaals' original comment with the checkboxes, but the i18n review is complete (pending the resolution of any outstanding issues).

The TAG reviews are also complete (pending any outstanding issues), and the Privacy IG and APA WG reviews returned no comments.


Ping @Siusin - did we receive any comments from the Security IG, after WebAppSec explained they didn't provide spec reviews?

@adanilo has been asigned the [issue on the HTML spec](https://github.com/w3c/html/issues/829), and (all things being equal) should have it done before HTML heads towards CR at the end of this month.

**Comment by siusin** [comment]
@LJWatson I [pinged the IG](https://lists.w3.org/Archives/Public/public-web-security/2017May/0000.html) again today (sorry I was on vacation last week), and I'll start preparing for the CR transition this week.

**Comment by LJWatson** [comment]
* A11y: no issues
* I18n: no issues
* Privacy: no issues
* Security: no response

The HTML spec was updated with [PR #963 Indexed seralize](https://github.com/w3c/html/pull/963). @inexorabletash, once the references have been updated in the IndexedDB spec, are there any other substantive issues we need to resolve before heading to CR?

**Comment by siusin** [comment]
+1

**Comment by inexorabletash** [comment]
None that I'm aware of.

(Is there existing magic to update the references? Bikeshed docs indicate that when the spec being processed is advanced beyond ED then it may automagically prefer different link defaults? May have to pester @tabatkins)

**Comment by aphillips** [comment]
It is wrong to say that I18N has no issues: we have 9 issues against IndexedDB. I have just now reviewed the disposition of these and think that you have addressed all but one (#173 which duplicates #38). You have also closed #180 but I haven't had time to review the examples to see if I agree with @inexorabletash yet. However, I think that issue is *at best* editorial and would not object to seeing your specification proceed.

I would like to see #38 addressed. Is your intention to handle this in a future revision?

**Comment by tabatkins** [comment]
> Bikeshed docs indicate that when the spec being processed is advanced beyond ED then it may automagically prefer different link defaults?

When you're using one of the W3C "TR statuses" (WD, CR, etc), then, per W3C's general policy, Bikeshed flips from preferring "current" references to preferring "snapshot" ones, when both exist for a given spec level.

**Comment by inexorabletash** [comment]
#38 is a request for additional functionality of substantial nature; there has not been significant demand from users of the API, nor sustained interest by implementers.

Should that change, it could indeed be addressed in a future revision, but is definitely out of scope for this edition.

**Comment by aphillips** [comment]
I agree that this is likely best assigned to the release "future".

I'm not sure that anyone has measured the significance of the demand or the interest of the developers. The nature of this change would require cross vendor incubation and planning in order to ensure interoperability. I do think this is somewhat important and shouldn't be put aside, but understand that I need to rally vendors.

That said, my original comment could be partially addressed by providing a code point sort.

**Comment by LJWatson** [comment]
@@aphillips sorry #38 was dropped, it wasn't intentional. The rest weren't included because they're closed.

Was your suggestion about the code point sort intended for inclusion in the current version, or as a way of resolving it in a future version?

Pending the answer to that question and @inexorabletash's response, and your review of the response to #180, we're ready to move to CR with this spec (and of course would like to do so sooner rather than later).

**Comment by LJWatson** [comment]
Ping @aphillips. We'd really like to move this spec to CR, so unless you think otherwise, I'll set things inmotion (with a WG CFC) later this week). Thanks

**Comment by aphillips** [comment]
@LJWatson I have no objection to your moving to CR. My main point on this thread was actually that you had addressed most of our issues. I agree that #38 can be for a future release, although I hope that release will be sooner rather than later. Good luck with your CFC.

**Comment by inexorabletash** [comment]
2.0 hit Rec, so closing this out.
