### ISSUE TITLE
Simplify "steps for storing a record into an object store"?

### ISSUE THREAD

**Issue by brettz9** [w3c/IndexedDB#144]
Unless I'm missing a conceptual or anticipated reason for specifying the steps this way, I'd think that step 1 of the "steps for storing a record into an object store" routine (i.e., "If store uses in-line keys, run these substeps:") could be removed and thereby limit some redundancy by having `IDBCursor.update` set `key` to `kpk` in its "If the effective object store of this cursor uses in-line keys, run these substeps:" routine immediately preceding its call to the record storing steps (as do `IDBObjectStore.put` and `IDBObjectStore.add` in their equivalent, corresponding step preceding the record storing steps), and then supply that `key` instead of the effective key as `key` to the record storing steps in such a case (assuming it is not a failure).

I know implementations could optimize the redundancy out anyways, but it seems it would be simpler conceptually as well unless I'm missing a reason for it.

**Comment by brettz9** [comment]
Btw, one nit for step 5...

> such that the list is sorted according key of the records in ascending order

should presumably be:

> such that the list is sorted according to the key of the records in ascending order

**Comment by brettz9** [comment]
And while I'm on the subject, for one other minor problem I see in the record storing steps, I think

> Otherwise, if the type of key is number and the value is greater than or equal to the key generator's current number, set the current number to lowest integer greater than key.

should be:

> Otherwise, if the type of key is number and the value is finite and greater than or equal to the key generator's current number, set the current number to the lowest integer greater than key.

**Comment by brettz9** [comment]
And if an exception is thrown in `inject a key into a value using a key path`, the consuming record storing steps don't indicate what to do with that exception.

**Comment by brettz9** [comment]
And I believe:

> Let keyValue be the result of running the steps to convert a key to a value.

ought to be:

> Let keyValue be the result of running the steps to convert a key to a value with `key` as `key`.

**Comment by inexorabletash** [comment]
Thank you very much @brettz9 for finding these. Nothing like a fresh implementation to shake out the glitches. I'll try and get a PR up this week to address these.

**Comment by inexorabletash** [comment]
>  ...having IDBCursor.update set _key_ to _kpk_...

This is not needed, as that block is responsible just checking that the extracted _key_ equals _effective key_. If not equal, the steps abort since `update()` is not allowed to modify a key. And_effective key_ is already passed as _key_. 

But agreed, step 1 in "steps for storing a record into an object store" is redundant.

----

> ... according to the key ...

Yep, will fix.

----

> ... value is finite ...

Wow, great catch. We don't appear to have web-platform-tests for this case. Chrome behaves as you suggest. Firefox fails dramatically on the next two puts - first a negative key then ConstraintError. Safari resets the key generator! Note that _finite_ is insufficient; behavior goes weird when above MAX_SAFE_INTEGER. I'll file a separate bug for this to get consensus on behavior.

-----

> ...exception is thrown in inject a key into a value using a key path...

Another good catch. This should never throw; the operation is run asynchronously so it doesn't make sense. The check needs to be pulled out and made explicit.

-----

> ...running the steps to convert a key to a value.

Will fix.
