### ISSUE TITLE
feature-request - add appendFile capability to overcome nedb performance-bottleneck

### ISSUE THREAD

**Issue by kaizhu256** [w3c/IndexedDB#260]
nedb emulates appendFile by re-saving its entire database as a blob to indexedb whenever a row insert/delete/update is performed [1].  this performance-hit makes it impractical for persisting largish datasets (> 20mb).

adding some kind of incremental appendFile feature would help.

[1] https://github.com/louischatriot/nedb/blob/v1.6.0/browser-version/browser-specific/lib/storage.js#L49

**Comment by kaizhu256** [comment]
this feature-request originated from https://github.com/tc39/proposal-javascript-standard-library/issues/16#issuecomment-457945120

**Comment by inexorabletash** [comment]
There are plans for a rebooted FileSystem API with both native and sandboxes support, which is probably a better fit, with the addition of locking primitives.

**Comment by pwnall** [comment]
Typical databases have some sort of block cache, and need to write modified blocks to disk. The sub-system is sometimes called the page cache or the pager.

If nedb has something similar, it should use a Blob for each block / size, instead of writing the entire database in a single Blob. Each block would be a Blob in an object store keyed by block ID. You can use this approach to build a database or a filesystem on top of IndexedDB. There's still overhead, but at least it's constant, not O(database size).

If you need something working soon, the approach above should give you some relief until we're able to build and ship the future APIs mentioned by @inexorabletash. I hope this helps!

**Comment by vweevers** [comment]
Off-topic: where can I follow progress on that rebooted FileSystem API? Thanks!

**Comment by inexorabletash** [comment]
https://github.com/WICG/native-file-system

**Comment by inexorabletash** [comment]
**TPAC 2019 Web Apps Indexed DB triage notes:**

We agree with advice in https://github.com/w3c/IndexedDB/issues/260#issuecomment-477488844 - implementations could also optimize blob storage using e.g. ropes.

There are explorations by Google Chrome of WASM-friendly storage APIs happening, which would allow running sqlite in the browser directly. Will add links if we can find them. And the people working on [native-file-system](https://github.com/WICG/native-file-system) would probably appreciate feedback too.

Mutable files doesn't seem to align well with the rest of Indexed DB and given the other possible approaches above, closing this out.

**Comment by kaizhu256** [comment]
cool, interested in links on sqlite3 when available.
