### ISSUE TITLE
[IndexedDB] WebAppsWG TPAC F2F agenda (Fukuoka, Sep 19-20 2019)

### ISSUE THREAD

**Issue by dmurph** [w3c/IndexedDB#288]
This is a **working draft** of the IndexedDB Agenda at TPAC, for the WebApps WG:

## Status Updates
* IndexedDBTransaction.commit shipped.

### Problem
IndexedDBTransaction's auto-commit mechanism is
1. confusing to users,
2. incompatible with Promises, and
3. incompatible with other async work.

While one could argue 3) is partially intentional, the other 2 are important problems that prevent more usage of IndexedDB.
### Proposal
Spec: TODO
Tracking: https://crbug.com/843769
IndexedDBTransaction.waitUntil (TODO: explainer / doc link)
Either implement waitUntil like the WebLocks API, or have an option on the transaction that disables auto-commit so the user has to call IndexedDBTransaction.commit
### Problem
All IndexedDB transactions guarantee flushing & syncing their data to disk. This is costly, and most websites don't need this functionality but pay the performance cost for it anyways.
Firefox was able to stop flushing by default, and currently requires developer opt-in for flushing. 
### Proposal
Spec: https://github.com/w3c/IndexedDB/issues/50
Tracking: https://crbug.com/965883
Introduce a flag for IndexedDB Transaction creation to specify to turn on flushing. (TODO: doc link).
### Problem
The IndexedDB specification has accumulated quite a few open issues, some of which are really old. Link: https://github.com/w3c/IndexedDB/issues/
### Proposal
We would like to have the community help us decide which issues are worth considering, and which issues can be closed.

**Comment by dmurph** [comment]
Attaching to the schedule here: w3c/webappswg#10

**Comment by inexorabletash** [comment]
Photos of flip chart of Indexed DB breakout at TPAC 2019 - transcription/notes to follow:

![image](https://user-images.githubusercontent.com/771547/65290166-1cb2e780-db89-11e9-9e8f-21a46fa74099.png)
![image](https://user-images.githubusercontent.com/771547/65290169-22103200-db89-11e9-9cc7-898e460691b4.png)
![image](https://user-images.githubusercontent.com/771547/65290180-2f2d2100-db89-11e9-8599-4599d50685d9.png)
![image](https://user-images.githubusercontent.com/771547/65290263-859a5f80-db89-11e9-9473-4725fb642ce5.png)
![image](https://user-images.githubusercontent.com/771547/65290269-8af7aa00-db89-11e9-822a-7cc6374ecb4d.png)
![image](https://user-images.githubusercontent.com/771547/65290280-964ad580-db89-11e9-9525-fe23a6397cd7.png)
![image](https://user-images.githubusercontent.com/771547/65290296-a793e200-db89-11e9-9813-20efe61974c6.png)

**Comment by inexorabletash** [comment]
TPAC 2019 Web Apps IndexedDB Breakout:

Topics discussed:

* `[SecureContext]` on commit() ? - notes in https://github.com/w3c/IndexedDB/issues/254
* Make autocommit optional - notes in https://github.com/w3c/IndexedDB/issues/34
* KV Storage
  * noted that there are performance concerns since IDB is "slow", but API is great
* Relaxed durability - notes in https://github.com/w3c/IndexedDB/issues/50
* Storing Response/Request objects
  * Mostly about just making them structured cloneable (bags of metadata + a blob)
  * For IDB, would need to define any special indexing - see table in https://w3c.github.io/IndexedDB/#key-path-construct
  * Follow-up: need tracking issue
* Issue backlog triage
  * desire to close out issues we think are not going to happen
  * planned for a day 2 breakout
* version change transactions w/o modifying version number
  * consensus on use case (e.g. PouchDB)
  * proposal: `open(DOMString name, optional [EnforceRange] unsigned long long version, optional DOMString smursion)`; upgrade runs if number is greater or smursion doesn't match. 
  * smursion is expected to be something like hash of database schema description; limited length string that's okay to cache in memory
  * we're not serious about `smursion` as a name :)
  * Follow-up: tracking bug, proposals
* getAll with key and primary key - notes in https://github.com/w3c/IndexedDB/issues/206
* putAll - notes in https://github.com/w3c/IndexedDB/issues/69
* getMany - notes in https://github.com/w3c/IndexedDB/issues/19

**Comment by inexorabletash** [comment]
Added tracking issues #304 #305
