### ISSUE TITLE
Add locale-aware sorting

### ISSUE THREAD

**Issue by annevk** [w3c/IndexedDB#38]
See https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Locale-aware_sorting and in particular https://bugzilla.mozilla.org/show_bug.cgi?id=871846 for details.

@reuben can probably help out if there are any questions.

**Comment by inexorabletash** [comment]
Yeah, I'd talked w/ bent about this. Thanks for filing it here.

The two big questions I had at the time were (1) stability of collations over time and (2) behavior of "auto" when device locale changes.

Copy/pasting from the old list: https://www.w3.org/2008/webapps/wiki/IndexedDatabaseFeatures

* Add 'locale' option to indexes (specified or 'platform')
* Add 'IDBLocaleAwareKeyRange' when querying such an index (doesn't enforce upper/lower order if both specified)
* Questions: are locales consistent across browsers? are collations stable?

**Comment by annevk** [comment]
I suspect the answers are no and no, but @aphillips can probably give a clearer answer.

**Comment by reuben** [comment]
No and no. Consistency depends on what versions of ICU browsers use and what locales they decide to ship. Collations change due to government regulations and new languages being introduced in the Unicode standard.

**Comment by aphillips** [comment]
Locales are not necessarily going to be consistent across browsers. The locales available to a given browser depends on the platform it is running on and/or implementation choices by the browser vendor. Not all browsers use ICU internally, for example. And different locales may or may not be provisioned on different host environments.

CLDR and the Unicode Collation Algorithm (UCA) do provide a basis for building and tailoring collations. These do evolve over time as the data is updated, new characters are added to Unicode, and so forth. Classical database vendors (such as Oracle for example) often go to great lengths to preserve existing collations in a stable manner. This is a good thing for their customers, but may not be suitable for the Web platform. Note that there are ways to tailoring ICU's implementation, at least, to be consistent (by providing the collation rules).

Also, UCA and CLDR describe additional settings (which can appear in a locale identifier courtesy of the 'u' extension of BCP 47 (cf. RFC 6067 and UTR#35)) beyond those in what you might be thinking of as "the locale" and these are also provided in the JavaScript internationalization extension. The JS folks felt that collation stability or even consistency was less important than being as close to end-user expectations at possible.

**Comment by sicking** [comment]
This means that we can't make an objectStore or a unique index be locale-sorted. Since whether two keys collide or not can change over time. In our implementation we only allow a non-unique indexes to be ordered using a specific (or auto) locale.

One problem in our API that I'd like to solve is that I think it should be possible to change the locale without upping the version of a database. I.e. if the user changes locale back and forth a few times, then that shouldn't require adding "artificial" version numbers to the database.

**Comment by inexorabletash** [comment]
Just pondering this... it definitely seems like the naive approach would be to let the collation be an option when creating an index and also add a method to modify it on an existing index, e.g.
```js
// I haven't looked at the Moz API here, so don't take this seriously
var index = store.createIndex('by_name', 'name', {unique:false, collation: 'de-u-co-phonebk'});
// or for existing indexes:
e.transaction.objectStore('products').index('by_model').collation = 'zh-Hans-SG';
```
... but agreed with @sicking that bumping the version to do the latter is unfortunate. I guess at a minimum it could be done within a readwrite transaction over the index's store, but that feels very odd if there are existing connections.

As a straw man to pick apart, we could pass an `{alter:true}` flag to open() that gives you an `alterneeded` event if the versions match. Same restrictions as upgrade transactions (exclusive, blocked/versionchange events, etc). I don't know if we'd want to artificially restrict the operations allowed in thesenversionchange transactions or not.

**Comment by aphillips** [comment]
@sicking Dealing with key equality can be done such that two distinctly encoded keys (that compare as equivalent according to UCA+tailoring) are not considered equal. There is a long section in [UTS10](http://www.unicode.org/reports/tr10/#Deterministic_Sorting) about the topic. Having this be stable could be a requirement.

A different consideration is whether two implementations need to produce identical sort orders given the same inputs (data values). If, say, FF has CLDR v28 and Chrome has CLDR v29, are they required to sort lists in the locale 'fr-FR' identically or not, if the underlying CLDR data has changed? Annual versions of Unicode and semi-annual ones of CLDR complicate this. But there is real value in providing locale-based sorting. That's why every relational database I know supports it. The interop guarantee is, I guess, the thorny issue here.

**Comment by hsivonen** [comment]
This functionality is being removed from Gecko. I suggest closing this as not planned.
