### ISSUE TITLE
Rewindable cursors

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#55]
(more details?)

Imported from https://www.w3.org/2008/webapps/wiki/IndexedDatabaseFeatures

**Comment by malibuzios** [comment]
One possible problem I see is that this would allow infinite transactions. E.g. one can move the cursor back and forth over two or more records forever in a loop.. (I don't mean this has to happen intentionally by the programmer - could just be some edge case that wasn't handled correctly)

I got impression the original design idea was that transactions would be short-termed and auto-closing?

Anyway this kind of relates to some of my comments on #72, where I questioned whether all transactions are supposed to be finite by design? To reiterate - the logic was: if all transactions were guaranteed to be finite (I'm excluding `open` and `close` requests here) then a `closePending` flag would mean that a `close` request would always cause a connection terminate to in a finite amount of time.

I thought I might as well mention that here as well?

**Comment by inexorabletash** [comment]
I clarified this with @malibuzios elsewhere (there was confusion about transaction lifetimes). This wouldn't add any new ability to extend the duration of a transaction.

But given the lack of further interest here, I'm going to close this out.
