### ISSUE TITLE
Redesign propagation path

### ISSUE THREAD

**Issue by annevk** [w3c/IndexedDB#66]
Apparently for some reason this specification uses UI Events to override the DOM Standard on some details of event dispatch. That seems extremely weird and wrong.

Having said that, DOM Standard doesn't have a hook yet for defining the propagation path (or event path as I suspect we'll end up calling it).

Would it work to have a hook where the event target defines the path? So that you invoke dispatch, dispatch asks the event target for the event path, and the event target returns a list of one or more objects implementing `EventTarget`. Or do you really need the thing you have now, where when you dispatch the event, you also provide the event path each time? (The latter kind of setup would not work at all well for DOM. That is, it would be very verbose.)

Paging @smaug---- since he might care about this.

**Comment by smaug----** [comment]
hmm, well, conceptually an event target doesn't define the whole path. An event target just knows about itself and the next item in the path. Usually node and the edge 'node->parentNode'.
IDB works the same way, since there is just one implementation to dispatch DOM events in Gecko at least. IDB dispatches event to target Foo, and among the first steps of dispatch event target chain (that happens to be what Gecko calls the propagation path) is created using a_target_in_chain -> next_target edges [1].
This setup lets event target to also filter out events. For example Document can return null as the next item in the chain when 'load' event is being dispatched somewhere in the DOM tree (since load is special). [2]

So it might be easiest to spec it so that each EventTarget has conceptual parent target.
By default null (for XHR, WebSocket etc), but Nodes would have parentNode, except in case of ShadowDOM, and some IDB objects would also have special parent.


[1] http://mxr.mozilla.org/mozilla-central/source/dom/indexedDB/IDBRequest.cpp?rev=e22b3043887e&mark=457-457#452
[2] http://mxr.mozilla.org/mozilla-central/source/dom/base/nsDocument.cpp?rev=6ecb187ce925&mark=8078-8083#8071

**Comment by annevk** [comment]
I figured the whole path might be easier for Shadow DOM since it currently defines obtaining the path as an algorithm, but we could probably change that somehow to just be an algorithm for finding the parent.

@hayatoito, does that seem reasonable?

**Comment by inexorabletash** [comment]
As additional data for non-IDB savvy on the thread: IDB "event paths" are always pretty simple:

* IDBRequest &rarr; IDBTransaction &rarr; IDBDatabase &mdash; _if event target is a request_
* IDBTransaction &rarr; IDBDatabase &mdash; _if event target is a transaction_

The "child" always has a reference to its "parent" when an event is being dispatched, and the relationship is immutable.

In Blink, for IDB, the path is indeed computed when the event is being dispatched to the target. But spec-wise, either approach (specifying a path or defining a "parent") seems fine with me. Once y'all figure out which is best I can make the change or PRs welcome.

**Comment by annevk** [comment]
I went with a "get the parent" algorithm associated with the `EventTarget` object. It gets passed an event mostly for the weird case of "load" and the `Window` object.
